<?php

namespace Feolius\Hell2Shape;

/**
 * Version information for hell2shape.
 * This file is automatically generated during release.
 * Do not edit manually.
 */
final class Version
{
    public const VERSION = '0.1.2';

    public const RELEASE_DATE = '2025-12-31';
}
