<?php

namespace Feolius\Hell2Shape;

/**
 * Version information for hell2shape.
 * This file is automatically generated during release.
 * Do not edit manually.
 */
final class Version
{
    public const VERSION = '0.3.0-test3';

    public const RELEASE_DATE = '2026-01-07';
}
